export const filters_fields = [
  {
    id: "height-inp",
    type: "slider",
    name: "height",
    placeholder: "الطول",
    label: "الطول",
    symobl: "CM",
  },
  {
    id: "weight-inp",
    type: "slider",
    name: "weight",
    placeholder: "الوزن",
    label: "الوزن",
    symobl: "KG",
  },
  {
    id: "skinColor-inp",
    type: "radiobox",
    name: "skin_color",
    placeholder: "لون البشرة",
    label: "لون البشرة",
    options: ["اشقر", "قمحي", "أسمر", "عربي", "اسمر افريقي"],
  },
  {
    id: "hairColor-inp",
    type: "radiobox",
    name: "hair_color",
    placeholder: "لون الشعر",
    label: "لون الشعر",
    options: ["ملون", "بني", "أسود"],
  },
  {
    id: "eyeColor-inp",
    type: "radiobox",
    name: "eye_color",
    placeholder: "لون العين",
    label: "لون العين",
    options: ["ملون", "بني", "أسود"],
  },
  {
    id: "hairType-inp",
    type: "radiobox",
    name: "hair_type",
    placeholder: "نوع الشعر",
    label: "نوع الشعر",
    options: ["ناعم", "عادي", "خشن"],
  },
  {
    id: "bodyShape-inp",
    type: "radiobox",
    name: "body_shape",
    placeholder: "شكل الجسم",
    label: "شكل الجسم",
    options: ["عادي", "رياضي"],
  },
  {
    id: "maritalStatus-inp",
    type: "radiobox",
    name: "marital_status",
    placeholder: "الحالة الاجتماعية",
    label: "الحالة الاجتماعية",
    options: ["متزوج", "عازب", "مطلق"],
  },
  {
    id: "generalHealth-inp",
    type: "radiobox",
    name: "general_health",
    placeholder: "الصحة العامة",
    label: "الصحة العامة",
    options: ["ممتاز", "جيد", "ضعيفة"],
  },
  {
    id: "hearing-inp",
    type: "radiobox",
    name: "hearing",
    placeholder: "الحواس الأساسية - السمع",
    label: "الحواس الأساسية - السمع",
    options: ["ممتاز", "جيد", "ضعيف", "أصم"],
  },
  {
    id: "vision-inp",
    type: "radiobox",
    name: "vision",
    placeholder: "الحواس الأساسية - البصر",
    label: "الحواس الأساسية - البصر",
    options: ["ممتاز", "جيد", "ضعيف", "كفيف"],
  },
  {
    id: "speech-inp",
    type: "radiobox",
    name: "speech",
    placeholder: "الحواس الأساسية - الكلام",
    label: "الحواس الأساسية - الكلام",
    options: ["ممتاز", "جيد", "ضعيف", "أبكم"],
  },
  {
    id: "signLanguage-inp",
    type: "radiobox",
    name: "sign_language",
    placeholder: "إجادة لغة الإشارة",
    label: "إجادة لغة الإشارة",
    options: ["نعم", "لا"],
  },
  {
    id: "chronicDiseases-inp",
    type: "radiobox",
    name: "chronic_diseases",
    placeholder: "يعاني من أمراض مزمنة",
    label: "يعاني من أمراض مزمنة",
    options: ["نعم", "لا"],
  },
  {
    id: "housingType-inp",
    type: "radiobox",
    name: "housing_type",
    placeholder: "نوع المسكن",
    label: "نوع المسكن",
    options: ["فيلا", "شقة"],
  },
  {
    id: "housingContractType-inp",
    type: "radiobox",
    name: "housing_contract_type",
    placeholder: "نوع عقد المسكن",
    label: "نوع عقد المسكن",
    options: ["إيجار جديد", "إيجار قديم", "تمليك"],
  },
  {
    id: "financialLevel-inp",
    type: "radiobox",
    name: "financial_level",
    placeholder: "المستوى المالي",
    label: "المستوى المالي",
    options: ["متيسر", "متوسط", "ضعيف"],
  },
  {
    id: "network-inp",
    type: "radiobox",
    name: "gift",
    placeholder: "شبكة",
    label: "شبكة",
    options: ["نعم", "لا", "حسب الاتفاق"],
  },
  {
    id: "mahr-inp",
    type: "radiobox",
    name: "mahr",
    placeholder: "المؤخر",
    label: "المؤخر",
    options: ["نعم", "لا", "حسب الاتفاق"],
  },
  {
    id: "witnesses-inp",
    type: "radiobox",
    name: "witnesses",
    placeholder: "قايمة",
    label: "قايمة",
    options: ["نعم", "لا", "حسب الاتفاق"],
  },
  {
    id: "maritalHome-inp",
    type: "radiobox",
    name: "marital_home",
    placeholder: "سكن زوجية",
    label: "سكن زوجية",
    options: ["نعم", "لا", "حسب الاتفاق"],
  },
  {
    id: "celebration-inp",
    type: "radiobox",
    name: "celebration",
    placeholder: "فرح",
    label: "فرح",
    options: ["نعم", "لا", "حسب الاتفاق"],
  },
  {
    id: "furniture-inp",
    type: "radiobox",
    name: "furniture",
    placeholder: "عفش",
    label: "عفش",
    options: ["نعم", "لا", "حسب الاتفاق"],
  },
];
